#Difusion en Reactor Tubular
J. Camilo Alfonso R., Carlos M. Patiño

In [50]:
%pylab inline
from mpl_toolkits.mplot3d import Axes3D ##library for 3d projection plots

Populating the interactive namespace from numpy and matplotlib


Las ecuaciones que corresponden al reactor son:
$$c_t=-u(r)c_z+D(c_{zz}+c_{rr}+\frac{1}{r}c_r)-r(c,T)$$
$$T_t=-u(r)T_z+\frac{\lambda}{\rho c_p}(T_{zz}+T_{rr}+\frac{1}{r}T_r)+\frac{-\Delta H}{\rho c_p}r(c,t)$$

## En el centro del reactor
$$r=0$$
$$u(r=0)=u_{max}\left(1-\left(\frac{0}{R}\right)^2\right)=u_{max}$$
Los siguientes terminos se puede recalcular usando el teorema de L'Hopital
$$\lim_{r\rightarrow0}{\frac{c_r}{r}=\frac{0}{0}}\rightarrow \lim_{r\rightarrow0}{\frac{c_r}{r}}=\lim_{r\rightarrow0}{\frac{\delta c_r/ \delta r}{\delta r/ \delta r}}=c_r$$
$$\lim_{r\rightarrow0}{\frac{T_r}{r}=\frac{0}{0}}\rightarrow \lim_{r\rightarrow0}{\frac{T_r}{r}}=\lim_{r\rightarrow0}{\frac{\delta T_r/ \delta r}{\delta r/ \delta r}}=T_r$$


Asi, se obtienen las ecuaciones:
$$c_t(r=0)=-u_{max}c_z+D(c_{zz}+2c_{rr}+)-r(c,T)$$
$$T_t(r=0)=-u_{max}T_z+\frac{\lambda}{\rho c_p}(T_{zz}+2T_{rr}+)+\frac{-\Delta H}{\rho c_p}r(c,t)$$

## Planteamiento Diferencias Finitas
Las ecuaciones que corresponden al reactor son:
$$c_t=-u(r)c_z+D(c_{zz}+c_{rr}+\frac{1}{r}c_r)-r(c,T)$$
$$T_t=-u(r)T_z+\frac{\lambda}{\rho c_p}(T_{zz}+T_{rr}+\frac{1}{r}T_r)+\frac{-\Delta H}{\rho c_p}r(c,t)$$

Sabiendo que las derivadas se pueden discretizar de la forma:
$$u_{i,j}^{n}=u(t=n,z=i,r=j)$$
$$\frac{\delta u}{\delta t} = \frac{u_{i,j}^{n+1}-u_{i,j}^{n}}{\Delta t}$$
$$\frac{\delta^2u}{\delta x^2}=\frac{u_{i+1,j}^{n}-2u_{i,j}^{n}+u_{i-1,j}^{n}}{\Delta x^2}$$

####Esquema Explicito
Se logra obtener el esquema explicito para $c_{i,j}^{n+1}$ y $T_{i,j}^{n+1}$
$$c_{i,j}^{n+1} = c_{i,j}^{n} -\frac{\Delta t}{\Delta z}u(r)(c_{i+1,j}^{n}-c_{i,j}^{n}) + D\Delta t \left(\frac{c_{i+1,j}^{n}-2c_{i,j}^{n}+c_{i-1,j}^{n}}{\Delta z^2} + \frac{c_{i,j+1}^{n}-2c_{i,j}^{n}+c_{i,j-1}^{n}}{\Delta r^2} + \frac{c_{i,j+1}^{n}-c_{i,j}^{n}}{r\Delta r}\right)-r\left(c_{i,j}^{n},T_{i,j}^{n}\right)$$

$$T_{i,j}^{n+1} = T_{i,j}^{n} -\frac{\Delta t}{\Delta z}u(r)(T_{i+1,j}^{n}-T_{i,j}^{n}) + \Delta t\frac{\lambda}{\rho c_p} \left(\frac{T_{i+1,j}^{n}-2T_{i,j}^{n}+T_{i-1,j}^{n}}{\Delta z^2} + \frac{T_{i,j+1}^{n}-2T_{i,j}^{n}+T_{i,j-1}^{n}}{\Delta r^2} + \frac{T_{i,j+1}^{n}-T_{i,j}^{n}}{r\Delta r}\right)+\Delta t\frac{-\Delta H}{\rho c_p}r\left(c_{i,j}^{n},T_{i,j}^{n}\right)$$

####Descripcion del sistema
Condiciones iniciales
$$c(z,r,0)=c_0(z,r)$$
$$T(z,r,0)=T_0(z,r)$$

Simetria Radial sin Transferencia de Masa
$$c_r(z,0,t)=\frac{c_{i,0+1}^{n}-c_{i,0}^{n}}{\Delta r}=0$$
$$\rightarrow c_{i,0}^{n}=c_{i,1}^{n}$$

$$T_r(z,0,t)=\frac{T_{j,0+1}^{n}-T_{j,0}^{n}}{\Delta r}=0$$
$$\rightarrow T_{j,0}^{n}=T_{j,1}^{n}$$

$$c_r(z,R,t)=\frac{c_{j,R}^{n}-c_{j,R-1}^{n}}{\Delta r}=0$$
$$\rightarrow c_{j,R}^{n}=c_{j,R-1}^{n}$$

Intercambio termico con la pared
$$T_r(z,R,t)=\frac{T_{j,R}^{n}-T_{j,R-1}^{n}}{\Delta r}=\frac{h}{\lambda}(T_w-T(z,R,t))$$
$$\rightarrow T_{i,R}^{n}=T_{i,R-1}^{n}+\Delta r \frac{h}{\lambda}(T_w-T_{i,R}^{n})$$

Concentracion y Temperatura constantes al **inicio** del tubo
$$c(0,r,t)=c_{0,j}^{n}=c_{in}$$
$$T(0,r,t)=T_{0,j}^{n}=T_{in}$$

Difusion cero a la salida
$$c_z(L,r,t)=\frac{c_{L,r}^{n}-c_{L-1,r}^{n}}{\Delta z}=0$$
$$\rightarrow c_{L,r}^{n} = c_{L-1,r}^{n}$$

$$T_z(L,r,t)=\frac{T_{L,i}^{n}-T_{L-1,i}^{n}}{\Delta z}=0$$
$$\rightarrow T_{L,r}^{n} = T_{L-1,r}^{n}$$

##Implementacion Diferencias Finitas
###Funciones

In [51]:
u_max = 1; # Velocidad Maxima
R = 4;     # Radio Maximo
def U_(r):
    # Velocidad en funcion del radio
    return u_max*(1-(r/R)**2)
#Verificar funcion u(r)
#r = linspace(-R,R,20)
#plot(r,U_(r))
# Funcion Verificada!

k0 = 1 # parametro
E = 1 # parametro
def F_r(c,T):
    return k0*exp(-E/(R*T))*c**2
    # Verificar si el 'R' de la ecuacion es el R_max del tubo o si es R constante de los gases

###Definir Arreglos

In [52]:
n_t = 10 # Numero de pasos en el tiempo
t_f = 2  # tiempo final
t = linspace(0,t_f,n_t) # vector de tiempo
d_t = t[1]-t[0] # paso de tiempo


n_r = 5
r = linspace(0,R,n_r) # El radio solo se evalua en la parte psotiva porque el comportamiento de las funciones respecto 
                        # al radio es simetrico
d_r = r[1] - r[0]


n_z = 8
L = 7 # Longitud del tubo
z = linspace(0,L,n_z)

zz,rr = meshgrid(z,r,sparse=False) # Malla

###Asignar Condiciones iniciales

In [103]:
#Tener cuidado con el tamaño de los arreglos rr y zz
def c_t0(z,r):
    #return ones(shape(z)) # Condicion en tiempo 0
    return z/10+r**2

def T_t0(z,r):
    #return ones(shape(z))
    return z/10+0.5*r**3

In [104]:
# Momento Inicial
# c y T se inicializan con las funciones dadas
T_in = 2
c_in = 2
h = 1 #Parametro
h2 = 1 #Lambda en ecuacion
T_w = 1 #Parametro

# Condicion Inicial
c_init =  c_t0(zz,rr)
T_init = T_t0(zz,rr)



c_present = c_init.copy()
T_present = T_init.copy()

# Condiciones de Frontera
# Simetria Radial sin trasnferencia de Masa
c_present[0,:] = c_present[1,:]
T_present[0,:] = T_present[1,:]
c_present[-1,:] = c_present[-2,:]

# Intercambio Termico en la pared
T_present[-1,:] = T_present[-2,:] + d_r*h/h2*(T_w-T_present[-1,:])

# Concentracion y Temperatura constantes al inicio del tubo
c_present[:,0] = c_in
T_present[:,0] = T_in

# Difusion cero a la salida
c_present[:,-1] = c_present[:,-2]
T_present[:,-1] = T_present[:,-2]

In [105]:
zz

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.]])

In [106]:
rr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])

In [107]:
c_present

array([[ 2. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.6],
       [ 2. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.6],
       [ 2. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.6],
       [ 2. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.6],
       [ 2. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.6]])

In [108]:
T_present

array([[  2. ,   0.6,   0.7,   0.8,   0.9,   1. ,   1.1,   1.1],
       [  2. ,   0.6,   0.7,   0.8,   0.9,   1. ,   1.1,   1.1],
       [  2. ,   4.1,   4.2,   4.3,   4.4,   4.5,   4.6,   4.6],
       [  2. ,  13.6,  13.7,  13.8,  13.9,  14. ,  14.1,  14.1],
       [  2. , -17.5, -17.5, -17.5, -17.5, -17.5, -17.5, -17.5]])